"""nimbus issue #390 (Mark Purcell), Forecaster-side half: a real transient
(his own case, a 43kW EV-charging spike) that legitimately dominates the
first few real-data-informed lag lookups could then get PERPETUATED
indefinitely once predict()'s recursive lag chain crosses
real_data_cutoff_utc and starts feeding purely its own prior predictions
back in as lag input -- confirmed live: the load forecast rose to
correctly track a real spike and then HELD at an elevated plateau for
26 minutes straight instead of ever reverting, because nothing in the
self-referential buffer_vals feedback loop pulled a runaway value back
toward what the signal has ever actually done.

This is the same class of bug as CLAUDE.md bug #3 (exposure bias fixed via
seasonal_lookup anchoring) -- but that fix only covers seasonal-anchored
subentries (power signals, plus one hardcoded whole-house sensor name),
leaving a plain per-circuit Load subentry (Mark's own case) fully exposed.

Fix: lag_at() now clamps a lookup to the signal's own real observed
range (+/- 20% margin, the same bound coordinator.py's own confidence-
band clamp already uses -- CLAUDE.md bug #5) -- but ONLY once the lookup
target is past real_data_cutoff_utc, i.e. only for self-generated values.
A genuine real reading (even a genuine extreme) is never touched.

Uses a hand-built "GBRT" stand-in whose predict() echoes its lag_short
input directly and unchanged -- a pure identity feedback loop, the
worst-case shape of the real bug (a real GBRT's own tree-based
extrapolation "getting stuck" on an out-of-distribution region, per
CLAUDE.md's own GBRT-vs-k-NN finding) and a clean, deterministic way to
prove the clamp is doing real work. A real k-NN would instead be
structurally bounded to y_train's own range regardless of any clamp
(same CLAUDE.md finding), which would make it impossible to tell
"clamped" apart from "k-NN's own convex-combination bound already did
it" -- confirmed directly: without the fix, this exact scenario holds
at the raw 40.0 spike value forever, all 20 steps, with nothing of its
own to ever pull it back down.
"""

from __future__ import annotations

import unittest
from datetime import datetime, timedelta

import _ml_path  # noqa: F401
import numpy as np
from nimbus_load.ml import model as ml_model

START_OF_TIME = datetime(2026, 1, 1, 0, 0, 0)  # noqa: DTZ001


class _StickyEchoGBRT:
    """Predicts lag_short directly, unchanged -- a pure identity echo.
    Once self-generated recursion takes over, this is a genuine, no-decay
    "hold whatever I last predicted forever" feedback loop with nothing
    to pull it back down on its own -- the exact worst-case shape of the
    real bug (a real GBRT's own tree-based extrapolation "getting stuck"
    on an out-of-distribution region, per CLAUDE.md's own GBRT-vs-k-NN
    finding), and a clean, deterministic way to prove the clamp is doing
    real work rather than relying on some other mechanism (e.g. a linear
    average naturally decaying on its own) to mask whether it's needed.
    """

    def predict(self, x_std: np.ndarray) -> np.ndarray:
        return x_std[:, 9].copy()


class TestRecursiveLagClamp(unittest.TestCase):
    def _build_trained_model(self) -> ml_model.TrainedModel:
        n_features = 16
        # Real observed range for this signal: 0-17kW (matches the
        # issue's own "site max in the 60-day window is ~17kW outside EV
        # sessions"). Clamp ceiling = 17 + 0.2*17 = 20.4.
        y_train = np.linspace(0.0, 17.0, 100)
        return ml_model.TrainedModel(
            model_type="gbrt",
            x_mean=np.zeros(n_features),
            x_std=np.ones(n_features),
            x_train=np.zeros((100, n_features)),
            y_train=y_train,
            gbrt=_StickyEchoGBRT(),
            trained_at=START_OF_TIME,
            training_points=100,
        )

    def setUp(self):
        self.trained = self._build_trained_model()
        self.forecast_start = START_OF_TIME
        # One real recent point, 15 minutes before forecast start, a real
        # 40kW spike (well above the 20.4 clamp ceiling) -- mirrors
        # Mark's own real ~43kW EV-charging transient.
        self.spike_value = 40.0
        self.recent_load_values = [
            (self.forecast_start - timedelta(minutes=15), self.spike_value)
        ]
        # 20 steps of 15 minutes = 5 real hours, comfortably past
        # LAG_LONG_STEPS (4 steps = 60 minutes) so recursion is fully
        # self-generated by the end of the horizon.
        self.n_steps = 20
        self.timestamps = [
            self.forecast_start + timedelta(minutes=15 * i) for i in range(self.n_steps)
        ]

    def _run(self) -> list[float]:
        result = ml_model.predict(
            trained=self.trained,
            timestamps=self.timestamps,
            temps=[20.0] * self.n_steps,
            humidities=[50.0] * self.n_steps,
            recent_load_values=self.recent_load_values,
            resample_minutes=15,
            allow_negative=False,
            seasonal_anchor=False,
        )
        return result.values

    def test_self_generated_recursion_converges_to_the_ceiling_not_the_spike(self):
        """Without the clamp, this exact scenario (verified directly via
        git stash before writing this test) holds at 40.0 -- the raw
        spike value -- for every single one of the 20 steps, forever:
        the identity-echo model has nothing of its own to ever pull a
        self-generated value back down, precisely reproducing "held at
        an elevated plateau" from the real issue. With the clamp, the
        (correctly, independently damping-smoothed -- CLAUDE.md bug #4)
        sequence instead decays cleanly from the real 40.0 toward the
        20.4 ceiling within a handful of steps and stays there."""
        values = self._run()
        ceiling = 20.4  # 17 + 0.2*17, see _build_trained_model
        # By step 5, real-data-informed damping has long since faded and
        # recursion is purely self-generated -- must be well below the
        # spike, not still anywhere near 40.0.
        self.assertLess(values[5], 25.0)
        # By step 10, fully converged to the ceiling.
        self.assertAlmostEqual(values[10], ceiling, delta=0.1)

    def test_late_horizon_settles_at_the_clamp_ceiling_not_the_spike(self):
        values = self._run()
        # A pure identity echo has NO mechanism of its own to ever move
        # off whatever value it's clamped to -- once self-generated
        # recursion takes over, every later step should sit right at the
        # ceiling (not still decaying toward it, and nowhere near the
        # original 40kW spike). Confirms the fix isn't just "eventually
        # helps" but genuinely stops the plateau on the very next step.
        self.assertAlmostEqual(values[-1], 20.4, delta=0.5)

    def test_real_recent_data_is_never_clamped(self):
        """The one step whose lag_short lookup targets EXACTLY the real
        recent point (not past real_data_cutoff_utc) must still reflect
        the real spike faithfully -- the clamp must never suppress
        genuine, real-data-informed history, only pure self-generated
        recursion."""
        values = self._run()
        # step 0: lag_short_v = spike_value (40.0, real, unclamped) fed
        # straight through by the identity-echo model -- proving the
        # real spike was not clamped away.
        self.assertAlmostEqual(values[0], 40.0, delta=1.0)


if __name__ == "__main__":
    unittest.main()
