retrain:
  fields:
    entity_id:
      selector:
        entity:
          integration: nimbus_load
          multiple: true
solve_now:
compute_quality_report:
  fields:
    start:
      required: true
      selector:
        datetime:
    end:
      required: true
      selector:
        datetime:
    allow_partial:
      default: true
      selector:
        boolean:
