retrain:
  fields:
    entity_id:
      selector:
        entity:
          integration: nimbus_load
          multiple: true
solve_now:
compute_quality_report:
  fields:
    start:
      required: true
      selector:
        datetime:
    end:
      required: true
      selector:
        datetime:
    allow_partial:
      default: true
      selector:
        boolean:

rescore_history:
  fields:
    days:
      default: 1
      selector:
        number:
          min: 1
          max: 30
          mode: box
