"""Spec DC-000 step 4: record legacy behaviour at a pinned commit.

    python scripts/device_contract_legacy.py <git-ref> \
        > tests/device_contract/snapshots/legacy/F09_power_units.json

Captures what the production power-unit code does at `<git-ref>` for every
unit case below, by executing that commit's own source (read with
`git show`, so the working tree is never consulted). The record is evidence
of current behaviour, defects included. It is never regenerated by a test
run: only this explicit, reviewed operation writes it (DC-000, "Record
legacy: capture only against an explicit baseline").

Deterministic: sorted keys, no timestamps.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from typing import Any

PKG = "custom_components/nimbus_load"
SOURCES = ("power_units.py", "power_input_check.py")

# Every spelling F09 asks about, plus the ones a household's template sensor
# plausibly produces. Strings only, then the non-strings.
UNITS: tuple[Any, ...] = (
    "mW",
    "W",
    "kW",
    "MW",
    "GW",
    "TW",
    "BTU/h",
    "w",
    "kw",
    "KW",
    "Kw",
    "mw",
    " kW ",
    "kWh",
    "Wh",
    "MWh",
    "kVA",
    "A",
    "",
    "furlong",
    None,
)


def _source(ref: str, name: str) -> str:
    return subprocess.run(
        ["git", "show", f"{ref}:{PKG}/{name}"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout


def _load(source: str) -> dict[str, Any]:
    ns: dict[str, Any] = {"__name__": "legacy"}
    exec(compile(source, "legacy", "exec"), ns)  # noqa: S102 -- pinned repo source
    return ns


def record(ref: str) -> dict[str, Any]:
    sha = subprocess.run(
        ["git", "rev-parse", f"{ref}^{{commit}}"],
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    srcs = {name: _source(sha, name) for name in SOURCES}
    units = _load(srcs["power_units.py"])
    check = _load(srcs["power_input_check.py"])
    cases = [
        {
            "unit": u,
            "is_power_unit": units["is_power_unit"](u),
            "scale_to_kw": units["power_scale_to_kw"](u),
            "is_energy_unit": check["is_energy_unit"](u),
        }
        for u in UNITS
    ]
    return {
        "fixture": "F09",
        "kind": "legacy_characterisation",
        "baseline": sha,
        "functions": [
            "power_units.is_power_unit",
            "power_units.power_scale_to_kw",
            "power_input_check.is_energy_unit",
        ],
        "source_sha256": {
            name: hashlib.sha256(text.replace("\r\n", "\n").encode()).hexdigest()
            for name, text in sorted(srcs.items())
        },
        "cases": cases,
    }


if __name__ == "__main__":
    out = record(sys.argv[1] if len(sys.argv) > 1 else "HEAD")
    sys.stdout.write(json.dumps(out, indent=1, sort_keys=True) + "\n")
